
let USERS={setupRequired:true,users:[]},LOGS={logs:[]},CURRENT=null,GHFILES={},GHCONNECTED=false;
const STORAGE_KEY="respectCFWGitHubConnectionV6";
async function sha256(s){const data=new TextEncoder().encode(s);const hash=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function randomSalt(){const a=new Uint8Array(16);crypto.getRandomValues(a);return [...a].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function passwordHash(pass,salt){return sha256(`${salt}:${pass}`)}
async function fetchJson(path){const r=await fetch(`${path}?ts=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(path);return r.json()}
async function loadAdminFiles(){[USERS,LOGS]=await Promise.all([fetchJson("users.json"),fetchJson("logs.json")]);$("setupOwnerBox").hidden=!USERS.setupRequired;$("normalLogin").hidden=USERS.setupRequired}
$("adminBtn").onclick=async()=>{try{await loadAdminFiles();$("adminModal").classList.add("open");$("loginView").hidden=false;$("dashboardView").hidden=true}catch(e){alert("Kunde inte läsa users.json/logs.json")}}
$("closeLogin").onclick=()=>$("adminModal").classList.remove("open");

async function login(){const email=$("loginEmail").value.trim().toLowerCase(),pass=$("loginPassword").value;const u=USERS.users.find(x=>x.email.toLowerCase()===email&&x.active!==false);if(!u)return $("loginStatus").textContent="Fel användare eller lösenord.";const h=await passwordHash(pass,u.salt);if(h!==u.passwordHash)return $("loginStatus").textContent="Fel användare eller lösenord.";CURRENT=u;await addLog("login","Logged in");openDashboard()}
$("loginBtn").onclick=login;

async function setupOwner(){if(!USERS.setupRequired)return;const name=$("setupName").value.trim(),email=$("setupEmail").value.trim().toLowerCase(),pass=$("setupPassword").value;if(!name||!email||pass.length<8)return alert("Fyll i namn, login och minst 8 teckens lösenord.");const salt=randomSalt();CURRENT={id:"owner",name,email,role:"owner",active:true,salt,passwordHash:await passwordHash(pass,salt),createdAt:new Date().toISOString()};USERS={version:1,setupRequired:false,users:[CURRENT]};if(!GHCONNECTED){alert("Anslut GitHub först så Owner-kontot kan sparas permanent. Öppnar admin så du kan göra det.");openDashboard();showPanel("github");return}await publishJson("users.json",USERS,"Create Respect CFW owner");await addLog("create_owner",email);openDashboard()}
$("setupOwnerBtn").onclick=setupOwner;

function openDashboard(){$("loginView").hidden=true;$("dashboardView").hidden=false;$("currentRole").textContent=CURRENT.role.toUpperCase();$("currentUser").textContent=CURRENT.name;$("usersTab").style.display=CURRENT.role==="owner"?"block":"none";loadCreds();fillAdmin();roleUI()}
function roleUI(){document.querySelector('[data-panel="payments"]').style.display=["owner","admin"].includes(CURRENT.role)?"block":"none";document.querySelector('[data-panel="products"]').style.display=["owner","admin","editor"].includes(CURRENT.role)?"block":"none";document.querySelector('[data-panel="content"]').style.display=["owner","admin","editor"].includes(CURRENT.role)?"block":"none";document.querySelector('[data-panel="github"]').style.display=CURRENT.role==="owner"?"block":"none"}
$("logoutBtn").onclick=()=>{CURRENT=null;$("adminModal").classList.remove("open")};$("closeAdmin").onclick=()=>$("adminModal").classList.remove("open");
document.querySelectorAll(".sideNav button").forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));
function showPanel(name){document.querySelectorAll(".sideNav button").forEach(b=>b.classList.toggle("active",b.dataset.panel===name));document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.id==="panel-"+name))}

function creds(){return{owner:$("ghOwner").value.trim(),repo:$("ghRepo").value.trim(),token:$("ghToken").value.trim()}}
function loadCreds(){try{const c=JSON.parse(localStorage.getItem(STORAGE_KEY));if(c){$("ghOwner").value=c.owner||"";$("ghRepo").value=c.repo||"";$("ghToken").value=c.token||""}}catch{}}
async function gh(path,opt={}){const c=creds();return fetch(`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}${path}`,{...opt,headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${c.token}`,"X-GitHub-Api-Version":"2022-11-28",...(opt.headers||{})}})}
function decode64(s){const bin=atob(s.replace(/\n/g,""));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function encode64Bytes(bytes){let bin="";for(let i=0;i<bytes.length;i++)bin+=String.fromCharCode(bytes[i]);return btoa(bin)}
function encode64Text(s){return encode64Bytes(new TextEncoder().encode(s))}
async function connectGitHub(){const c=creds();if(!c.owner||!c.repo||!c.token)return $("ghStatus").textContent="Fyll i alla tre fälten.";$("ghStatus").textContent="Ansluter…";try{for(const file of ["data.json","users.json","logs.json"]){const r=await gh(`/contents/${file}`);if(!r.ok)throw new Error(file);const j=await r.json();GHFILES[file]={sha:j.sha}}localStorage.setItem(STORAGE_KEY,JSON.stringify(c));GHCONNECTED=true;$("ghStatus").textContent="Ansluten. Ändringar kan publiceras direkt.";updateConnection();}catch(e){GHCONNECTED=false;$("ghStatus").textContent=`Kunde inte ansluta (${e.message}). Kontrollera token och repository.`}}
$("connectGithub").onclick=connectGitHub;$("forgetGithub").onclick=()=>{localStorage.removeItem(STORAGE_KEY);$("ghOwner").value=$("ghRepo").value=$("ghToken").value="";GHCONNECTED=false;GHFILES={};$("ghStatus").textContent="Anslutningen är borttagen.";updateConnection()}
async function ensureGitHub(){if(GHCONNECTED)return true;loadCreds();if(!$("ghToken").value)return false;await connectGitHub();return GHCONNECTED}
async function getSha(path){if(GHFILES[path]?.sha)return GHFILES[path].sha;const r=await gh(`/contents/${path}`);if(r.status===404)return null;if(!r.ok)throw new Error(`Cannot read ${path}`);const j=await r.json();GHFILES[path]={sha:j.sha};return j.sha}
async function putFile(path,contentBase64,message){const sha=await getSha(path);const body={message,content:contentBase64};if(sha)body.sha=sha;const r=await gh(`/contents/${path}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){const x=await r.text();throw new Error(x)}const j=await r.json();GHFILES[path]={sha:j.content.sha};return j}
async function publishJson(path,obj,message){if(!(await ensureGitHub()))throw new Error("GitHub är inte anslutet");return putFile(path,encode64Text(JSON.stringify(obj,null,2)),message)}
async function addLog(action,detail){if(!CURRENT)return;try{LOGS=await fetchJson("logs.json")}catch{}LOGS.logs.unshift({id:Date.now()+"-"+Math.random().toString(16).slice(2),time:new Date().toISOString(),userId:CURRENT.id,user:CURRENT.name,email:CURRENT.email,action,detail});LOGS.logs=LOGS.logs.slice(0,500);if(await ensureGitHub())await publishJson("logs.json",LOGS,`Respect CFW log: ${action}`);renderLogs()}

function updateConnection(){$("connectionSummary").textContent=GHCONNECTED?"GitHub: ansluten – permanenta ändringar kan publiceras.":"GitHub: inte ansluten på denna enhet."}
function fillAdmin(){$("arHeroA").value=SITE.content.ar.heroA;$("enHeroA").value=SITE.content.en.heroA;$("arHeroB").value=SITE.content.ar.heroB;$("enHeroB").value=SITE.content.en.heroB;$("arHeroText").value=SITE.content.ar.heroText;$("enHeroText").value=SITE.content.en.heroText;$("revolutUrl").value=SITE.store.revolutUrl||"";$("paypalUrl").value=SITE.store.paypalUrl||"";$("currency").value=SITE.store.currency||"$";renderProductEditors();renderUsers();renderLogs();updateConnection()}
function renderProductEditors(){$("productEditors").innerHTML=SITE.products.map((p,i)=>`<div class="editor" data-index="${i}"><div class="editorHead"><h3>${esc(p.titleEn)}</h3><button class="btn danger" onclick="removeProduct(${i})">Ta bort</button></div><div class="two"><div class="field"><label>Titel AR</label><input data-k="titleAr" value="${esc(p.titleAr)}"></div><div class="field"><label>Titel EN</label><input data-k="titleEn" value="${esc(p.titleEn)}"></div><div class="field full"><label>Beskrivning AR</label><textarea data-k="descAr">${esc(p.descAr)}</textarea></div><div class="field full"><label>Beskrivning EN</label><textarea data-k="descEn">${esc(p.descEn)}</textarea></div><div class="field"><label>Pris</label><input data-k="price" type="number" step=".01" value="${p.price}"></div><div class="field"><label>Ordinarie pris</label><input data-k="oldPrice" type="number" step=".01" value="${p.oldPrice||0}"></div><div class="field"><label>Framework</label><input data-k="framework" value="${esc(p.framework)}"></div><div class="field"><label>Version</label><input data-k="version" value="${esc(p.version)}"></div><div class="field"><label>Badge AR</label><input data-k="badgeAr" value="${esc(p.badgeAr)}"></div><div class="field"><label>Badge EN</label><input data-k="badgeEn" value="${esc(p.badgeEn)}"></div><div class="field full"><label>Funktioner AR, en per rad</label><textarea data-k="featuresAr">${esc((p.featuresAr||[]).join("\n"))}</textarea></div><div class="field full"><label>Funktioner EN, en per rad</label><textarea data-k="featuresEn">${esc((p.featuresEn||[]).join("\n"))}</textarea></div><div class="field full"><label>Bilder / kort video</label><input type="file" accept="image/*,video/mp4,video/webm" multiple onchange="uploadMedia(${i},this.files)"><div class="mediaRow">${(p.media||[]).map((m,mi)=>`<div class="preview">${m.type==="video"?`<video src="${esc(m.url)}" muted></video>`:`<img src="${esc(m.url)}">`}<button class="removeMedia" onclick="removeMedia(${i},${mi})">✕</button></div>`).join("")}</div></div></div></div>`).join("")}
function collectProducts(){document.querySelectorAll(".editor").forEach((box,i)=>box.querySelectorAll("[data-k]").forEach(inp=>{let v=inp.value,k=inp.dataset.k;if(["price","oldPrice"].includes(k))v=Number(v)||0;if(["featuresAr","featuresEn"].includes(k))v=v.split("\n").map(x=>x.trim()).filter(Boolean);SITE.products[i][k]=v}))}
$("addProduct").onclick=()=>{SITE.products.push({id:"product-"+Date.now(),titleAr:"منتج جديد",titleEn:"New Product",descAr:"وصف المنتج",descEn:"Product description",price:19.99,oldPrice:0,framework:"Standalone",version:"1.0.0",badgeAr:"جديد",badgeEn:"New",featuresAr:[],featuresEn:[],media:[]});renderProductEditors()}
window.removeProduct=i=>{if(confirm("Ta bort produkten?")){SITE.products.splice(i,1);renderProductEditors()}}
$("saveProducts").onclick=async()=>{try{collectProducts();await publishJson("data.json",SITE,"Update Respect CFW products");await addLog("update_products",`${SITE.products.length} products`);renderSite();alert("Produkter publicerade till GitHub.")}catch(e){alert(e.message)}}

window.uploadMedia=async(i,files)=>{if(!(await ensureGitHub()))return alert("Anslut GitHub först.");for(const file of [...files]){if(file.size>20*1024*1024){alert(`${file.name}: max 20 MB`);continue}const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=`assets/${SITE.products[i].id}/${Date.now()}-${safe}`,bytes=new Uint8Array(await file.arrayBuffer());try{await putFile(path,encode64Bytes(bytes),`Upload media for ${SITE.products[i].titleEn}`);SITE.products[i].media=SITE.products[i].media||[];SITE.products[i].media.push({type:file.type.startsWith("video")?"video":"image",url:path,name:file.name});await addLog("upload_media",path)}catch(e){alert(`Upload failed: ${e.message}`)}}await publishJson("data.json",SITE,"Attach product media");renderProductEditors();renderSite()}
window.removeMedia=async(i,mi)=>{const m=SITE.products[i].media[mi];if(!confirm("Ta bort media från produkten?"))return;SITE.products[i].media.splice(mi,1);try{await publishJson("data.json",SITE,"Remove product media reference");await addLog("remove_media",m.url);renderProductEditors();renderSite()}catch(e){alert(e.message)}}

$("saveContent").onclick=async()=>{SITE.content.ar.heroA=$("arHeroA").value;SITE.content.en.heroA=$("enHeroA").value;SITE.content.ar.heroB=$("arHeroB").value;SITE.content.en.heroB=$("enHeroB").value;SITE.content.ar.heroText=$("arHeroText").value;SITE.content.en.heroText=$("enHeroText").value;try{await publishJson("data.json",SITE,"Update Respect CFW content");await addLog("update_content","Homepage content");renderSite();alert("Hemsidan publicerad.")}catch(e){alert(e.message)}}
$("savePayments").onclick=async()=>{SITE.store.revolutUrl=$("revolutUrl").value.trim();SITE.store.paypalUrl=$("paypalUrl").value.trim();SITE.store.currency=$("currency").value;try{await publishJson("data.json",SITE,"Update Respect CFW checkout");await addLog("update_checkout","Payment settings");renderSite();alert("Checkout publicerad.")}catch(e){alert(e.message)}}

function renderUsers(){$("userRows").innerHTML=USERS.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${esc(u.role)}</td><td>${u.active!==false?"Aktiv":"Avstängd"}</td><td>${u.role==="owner"?"Owner":`<button class="btn danger" onclick="toggleUser('${u.id}')">${u.active!==false?"Stäng av":"Aktivera"}</button>`}</td></tr>`).join("")}
$("createUser").onclick=async()=>{if(CURRENT.role!=="owner")return;const name=$("newName").value.trim(),email=$("newEmail").value.trim().toLowerCase(),pass=$("newPass").value,role=$("newRole").value;if(!name||!email||pass.length<8)return alert("Minst 8 teckens lösenord.");if(USERS.users.some(u=>u.email.toLowerCase()===email))return alert("Användaren finns redan.");const salt=randomSalt();USERS.users.push({id:"u-"+Date.now(),name,email,role,active:true,salt,passwordHash:await passwordHash(pass,salt),createdAt:new Date().toISOString()});try{await publishJson("users.json",USERS,"Create Respect CFW admin user");await addLog("create_user",`${email} (${role})`);renderUsers();alert("Användaren är skapad och sparad på GitHub.")}catch(e){alert(e.message)}}
window.toggleUser=async id=>{if(CURRENT.role!=="owner")return;const u=USERS.users.find(x=>x.id===id);if(!u||u.role==="owner")return;u.active=!u.active;await publishJson("users.json",USERS,"Update Respect CFW user");await addLog("update_user",`${u.email}: ${u.active?"active":"disabled"}`);renderUsers()}
$("changePassword").onclick=async()=>{const a=$("changePass1").value,b=$("changePass2").value;if(a.length<8)return alert("Minst 8 tecken.");if(a!==b)return alert("Lösenorden matchar inte.");const u=USERS.users.find(x=>x.id===CURRENT.id),salt=randomSalt();u.salt=salt;u.passwordHash=await passwordHash(a,salt);try{await publishJson("users.json",USERS,"Change Respect CFW password");await addLog("change_password",CURRENT.email);alert("Lösenordet är ändrat och publicerat.")}catch(e){alert(e.message)}}

function renderLogs(){$("logRows").innerHTML=(LOGS.logs||[]).map(l=>`<tr><td>${new Date(l.time).toLocaleString()}</td><td>${esc(l.user)}</td><td>${esc(l.action)}</td><td>${esc(l.detail)}</td></tr>`).join("")}
loadCreds();
