const cfg=window.BLENDXO_CONFIG||{}; const isSupabase=cfg.mode==='supabase'&&cfg.supabaseUrl&&cfg.supabaseAnonKey; const sb=isSupabase?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const DEFAULT_SERVICES=[{id:'taper',name:'Taper Fade',price:200,duration:45,active:true},{id:'low',name:'Low Fade',price:200,duration:45,active:true},{id:'mid',name:'Mid Fade',price:200,duration:45,active:true},{id:'high',name:'High Fade',price:200,duration:45,active:true},{id:'fade-beard',name:'Fade + Skägg',price:250,duration:60,active:true},{id:'beard',name:'Endast skägg',price:150,duration:30,active:true}];
const keys=['hero','about','gallery1','gallery2','gallery3','gallery4']; const labels={hero:'Hero / startsida',about:'Om-sektion',gallery1:'Galleri 1',gallery2:'Galleri 2',gallery3:'Galleri 3',gallery4:'Galleri 4'};
function readLocal(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}} function saveLocal(k,v){localStorage.setItem(k,JSON.stringify(v))} function esc(v=''){return String(v).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));}
async function login(email,password){if(isSupabase){const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;return true;} if(email==='admin@blendxo.se'&&password==='blendxo'){sessionStorage.setItem('blendxo_admin','1');return true;}throw new Error('Fel e-post eller lösenord');}
async function logout(){if(isSupabase)await sb.auth.signOut();sessionStorage.removeItem('blendxo_admin');location.reload();}
async function authed(){if(isSupabase){const {data}=await sb.auth.getSession();return !!data.session;}return sessionStorage.getItem('blendxo_admin')==='1';}
async function services(){if(isSupabase){const {data}=await sb.from('services').select('*').order('sort_order');return data||[];}return readLocal('blendxo_services',DEFAULT_SERVICES)}
async function saveServices(list){if(isSupabase){for(let i=0;i<list.length;i++){await sb.from('services').upsert({...list[i],sort_order:i});}}else saveLocal('blendxo_services',list)}
async function bookings(){if(isSupabase){const {data}=await sb.from('bookings').select('*').order('booking_date',{ascending:false}).order('booking_time',{ascending:false});return data||[];}return readLocal('blendxo_bookings',[])}
async function setStatus(id,status){if(isSupabase){await sb.from('bookings').update({status}).eq('id',id)}else{const all=readLocal('blendxo_bookings',[]).map(x=>x.id===id?{...x,status}:x);saveLocal('blendxo_bookings',all)}}
async function images(){if(isSupabase){const {data}=await sb.from('site_images').select('*');return Object.fromEntries((data||[]).map(x=>[x.image_key,x.url]));}return readLocal('blendxo_images',{})}
async function uploadImage(key,file){if(isSupabase){const ext=file.name.split('.').pop();const path=`${key}-${Date.now()}.${ext}`;const {error}=await sb.storage.from('site-images').upload(path,file,{upsert:true});if(error)throw error;const {data}=sb.storage.from('site-images').getPublicUrl(path);await sb.from('site_images').upsert({image_key:key,url:data.publicUrl});return data.publicUrl;}return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const all=readLocal('blendxo_images',{});all[key]=r.result;saveLocal('blendxo_images',all);resolve(r.result)};r.onerror=reject;r.readAsDataURL(file)})}
async function removeImage(key){if(isSupabase)await sb.from('site_images').delete().eq('image_key',key);else{const all=readLocal('blendxo_images',{});delete all[key];saveLocal('blendxo_images',all)}}

function showAdmin(){document.getElementById('loginView').classList.add('hidden');document.getElementById('adminView').classList.remove('hidden');renderAll()}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await login(email.value,password.value);showAdmin()}catch(err){document.getElementById('loginError').textContent=err.message}});document.getElementById('logoutBtn').onclick=logout;if(isSupabase)document.getElementById('demoHint').classList.add('hidden');
document.querySelectorAll('.nav-btn[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.admin-tab').forEach(x=>x.classList.toggle('hidden',x.dataset.panel!==b.dataset.tab));document.getElementById('tabTitle').textContent=b.textContent;});

async function renderAll(){await Promise.all([renderBookings(),renderServices(),renderImages()]);}
async function renderBookings(){const all=await bookings();const today=new Date().toISOString().split('T')[0];document.getElementById('statUpcoming').textContent=all.filter(x=>x.booking_date>=today&&x.status!=='cancelled').length;document.getElementById('statToday').textContent=all.filter(x=>x.booking_date===today&&x.status!=='cancelled').length;const rows=all.map(b=>`<div class="booking-row"><div><b>${esc(b.booking_time)} • ${esc(b.customer_name)}</b><small>${esc(b.booking_date)} • ${esc(b.service_name||b.service_id)} • ${esc(b.phone)}</small></div><span class="status ${esc(b.status||'pending')}">${esc(b.status||'pending')}</span><div class="row-actions"><button onclick="changeStatus('${b.id}','confirmed')">Bekräfta</button><button onclick="changeStatus('${b.id}','cancelled')">Avboka</button></div></div>`).join('')||'<div class="empty">Inga bokningar ännu.</div>';document.getElementById('bookingsTable').innerHTML=rows;document.getElementById('latestBookings').innerHTML=rows.split('</div>').slice(0,12).join('</div>');}
window.changeStatus=async(id,status)=>{await setStatus(id,status);await renderBookings()};document.getElementById('refreshBookings').onclick=renderBookings;
async function renderServices(){const list=await services();document.getElementById('statServices').textContent=list.length;const ed=document.getElementById('serviceEditor');ed.innerHTML=list.map((s,i)=>`<div class="service-edit" data-i="${i}"><input class="svc-name" value="${esc(s.name)}"><input class="svc-price" type="number" value="${s.price}"><input class="svc-duration" type="number" value="${s.duration}"><label class="toggle"><input class="svc-active" type="checkbox" ${s.active!==false?'checked':''}> Aktiv</label><button class="danger" onclick="deleteService(${i})">Ta bort</button></div>`).join('')+'<button class="btn full" id="saveServicesBtn">Spara tjänster</button>';document.getElementById('saveServicesBtn').onclick=async()=>{const current=await services();const vals=[...document.querySelectorAll('.service-edit')].map((r,i)=>({id:current[i]?.id||crypto.randomUUID(),name:r.querySelector('.svc-name').value.trim(),price:Number(r.querySelector('.svc-price').value),duration:Number(r.querySelector('.svc-duration').value),active:r.querySelector('.svc-active').checked}));await saveServices(vals);alert('Tjänster sparade.');renderServices()};}
window.deleteService=async i=>{const list=await services();list.splice(i,1);await saveServices(list);renderServices()};document.getElementById('addServiceBtn').onclick=async()=>{const list=await services();list.push({id:crypto.randomUUID(),name:'Ny tjänst',price:200,duration:45,active:true});await saveServices(list);renderServices()};
async function renderImages(){const imgs=await images();document.getElementById('imageEditor').innerHTML=keys.map(k=>`<div class="image-admin-card"><div class="image-preview ${imgs[k]?'has-image':''}" ${imgs[k]?`style="background-image:url('${imgs[k]}')"`:''}><span>${esc(labels[k])}</span></div><label class="upload-btn">Byt bild<input type="file" accept="image/*" data-key="${k}"></label><button class="danger" onclick="deleteImage('${k}')">Ta bort</button></div>`).join('');document.querySelectorAll('input[type=file][data-key]').forEach(input=>input.onchange=async()=>{const f=input.files[0];if(!f)return;try{await uploadImage(input.dataset.key,f);await renderImages()}catch(e){alert('Uppladdningen misslyckades: '+e.message)}})}
window.deleteImage=async k=>{await removeImage(k);renderImages()};
(async()=>{if(await authed())showAdmin()})();
