const cfg=window.BLENDXO_CONFIG||{},configured=cfg.mode==='supabase'&&cfg.supabaseUrl&&cfg.supabaseAnonKey,sb=configured?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const keys=['hero','about','gallery1','gallery2','gallery3','gallery4'],labels={hero:'Hero / startsida',about:'Om-sektion',gallery1:'Galleri 1',gallery2:'Galleri 2',gallery3:'Galleri 3',gallery4:'Galleri 4'};
const esc=(v='')=>String(v).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
async function authed(){if(!configured)return false;const{data}=await sb.auth.getSession();return!!data.session}
async function isAdmin(){const{data,error}=await sb.rpc('is_admin');return !error&&data===true}
async function login(email,password){if(!configured)throw Error('Supabase är inte konfigurerat.');const{error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;if(!await isAdmin()){await sb.auth.signOut();throw Error('Kontot saknar adminbehörighet.')}}
async function logout(){await sb.auth.signOut();location.reload()}
async function services(){const{data,error}=await sb.from('services').select('*').order('sort_order');if(error)throw error;return data||[]}
async function saveServices(list){for(let i=0;i<list.length;i++){const{error}=await sb.from('services').upsert({...list[i],sort_order:i});if(error)throw error}}
async function bookings(){const{data,error}=await sb.from('bookings').select('*').order('booking_date',{ascending:false}).order('booking_time',{ascending:false});if(error)throw error;return data||[]}
async function setStatus(id,status){const{error}=await sb.from('bookings').update({status}).eq('id',id);if(error)throw error}
async function images(){const{data,error}=await sb.from('site_images').select('*');if(error)throw error;return Object.fromEntries((data||[]).map(x=>[x.image_key,x]))}
async function uploadImage(key,file){
  if(!file.type.startsWith('image/'))throw Error('Välj en bildfil.');
  if(file.size>8*1024*1024)throw Error('Bilden är för stor. Max 8 MB.');
  const old=(await images())[key];
  const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${key}/${crypto.randomUUID()}.${ext}`;
  const{error}=await sb.storage.from('site-images').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;
  const{data}=sb.storage.from('site-images').getPublicUrl(path);
  const{error:e2}=await sb.from('site_images').upsert({image_key:key,url:data.publicUrl,storage_path:path,updated_at:new Date().toISOString()});if(e2)throw e2;
  if(old?.storage_path)await sb.storage.from('site-images').remove([old.storage_path]);
}
async function removeImage(key){const old=(await images())[key];if(old?.storage_path)await sb.storage.from('site-images').remove([old.storage_path]);const{error}=await sb.from('site_images').delete().eq('image_key',key);if(error)throw error}
async function getSettings(){const{data,error}=await sb.from('site_settings').select('setting_key,setting_value');if(error)throw error;return Object.fromEntries((data||[]).map(x=>[x.setting_key,x.setting_value||'']))}
async function saveSetting(setting_key,setting_value){const{error}=await sb.from('site_settings').upsert({setting_key,setting_value,updated_at:new Date().toISOString()});if(error)throw error}
async function showAdmin(){if(!await isAdmin())return;document.getElementById('loginView').classList.add('hidden');document.getElementById('adminView').classList.remove('hidden');renderAll()}

document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();try{await login(email.value,password.value);showAdmin()}catch(err){loginError.textContent=err.message}};
document.getElementById('logoutBtn').onclick=logout;
document.getElementById('forgotPasswordBtn').onclick=async()=>{const mail=email.value.trim();if(!mail)return alert('Skriv din e-postadress först.');try{const{error}=await sb.auth.resetPasswordForEmail(mail,{redirectTo:location.origin+location.pathname});if(error)throw error;alert('Återställningslänk skickad.')}catch(e){alert(e.message)}};
document.querySelectorAll('.nav-btn[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.admin-tab').forEach(x=>x.classList.toggle('hidden',x.dataset.panel!==b.dataset.tab));tabTitle.textContent=b.textContent});
async function renderAll(){await Promise.all([renderBookings(),renderServices(),renderImages(),renderSettings()])}
async function renderBookings(){const all=await bookings(),today=new Date().toISOString().split('T')[0];statUpcoming.textContent=all.filter(x=>x.booking_date>=today&&x.status!=='cancelled').length;statToday.textContent=all.filter(x=>x.booking_date===today&&x.status!=='cancelled').length;const rows=all.map(b=>`<div class="booking-row"><div><b>${esc(b.booking_time)} • ${esc(b.customer_name)}</b><small>${esc(b.booking_date)} • ${esc(b.service_name)} • ${esc(b.phone)}</small></div><span class="status ${esc(b.status)}">${esc(b.status)}</span><div class="row-actions"><button onclick="changeStatus('${b.id}','confirmed')">Bekräfta</button><button onclick="changeStatus('${b.id}','cancelled')">Avboka</button></div></div>`).join('')||'<div class="empty">Inga bokningar ännu.</div>';bookingsTable.innerHTML=rows;latestBookings.innerHTML=rows}
window.changeStatus=async(id,status)=>{await setStatus(id,status);renderBookings()};refreshBookings.onclick=renderBookings;
async function renderServices(){const list=await services();statServices.textContent=list.length;serviceEditor.innerHTML=list.map((s,i)=>`<div class="service-edit" data-i="${i}"><input class="svc-name" value="${esc(s.name)}" aria-label="Tjänst"><input class="svc-price" type="number" min="0" value="${s.price}" aria-label="Pris"><input class="svc-duration" type="number" min="5" step="5" value="${s.duration}" aria-label="Minuter"><label class="toggle"><input class="svc-active" type="checkbox" ${s.active?'checked':''}> Aktiv</label><button class="danger" onclick="deleteService(${i})">Ta bort</button></div>`).join('')+'<button class="btn full" id="saveServicesBtn">Spara tjänster</button>';saveServicesBtn.onclick=async()=>{const current=await services(),vals=[...document.querySelectorAll('.service-edit')].map((r,i)=>({id:current[i]?.id||crypto.randomUUID(),name:r.querySelector('.svc-name').value.trim(),price:+r.querySelector('.svc-price').value,duration:+r.querySelector('.svc-duration').value,active:r.querySelector('.svc-active').checked}));await saveServices(vals);alert('Tjänster sparade.');renderServices()}}
window.deleteService=async i=>{if(!confirm('Ta bort tjänsten?'))return;const list=await services();await sb.from('services').delete().eq('id',list[i].id);renderServices()};addServiceBtn.onclick=async()=>{await sb.from('services').insert({id:crypto.randomUUID(),name:'Ny tjänst',price:200,duration:45,active:true,sort_order:(await services()).length});renderServices()};
async function renderImages(){const imgs=await images();imageEditor.innerHTML=keys.map(k=>`<div class="image-admin-card"><div class="image-preview ${imgs[k]?'has-image':''}" ${imgs[k]?`style="background-image:url('${imgs[k].url}')"`:''}><span>${esc(labels[k])}</span></div><label class="upload-btn">📷 Välj bild från enheten<input type="file" accept="image/jpeg,image/png,image/webp" data-key="${k}"></label><small class="upload-status" id="upload-${k}">JPG, PNG eller WEBP • max 8 MB</small>${imgs[k]?`<a class="link-btn" href="${imgs[k].url}" target="_blank" rel="noopener">Visa aktuell bild</a>`:''}<button class="danger" onclick="deleteImage('${k}')">Ta bort bild</button></div>`).join('');document.querySelectorAll('input[type=file][data-key]').forEach(i=>i.onchange=async()=>{if(!i.files[0])return;const status=document.getElementById(`upload-${i.dataset.key}`);try{status.textContent='Laddar upp…';await uploadImage(i.dataset.key,i.files[0]);status.textContent='Uppladdad ✓';await renderImages()}catch(e){status.textContent='Fel: '+e.message}})}
window.deleteImage=async k=>{if(!confirm('Ta bort bilden från hemsidan?'))return;await removeImage(k);renderImages()};
async function renderSettings(){try{const s=await getSettings();contactPhone.value=s.contact_phone||'070-487 70 05';instagramHandle.value=s.instagram_handle||'@blendxo_';whatsappNumber.value=s.whatsapp_number||'';notificationEmail.value=s.notification_email||''}catch(e){settingsMessage.textContent='Kunde inte läsa inställningar: '+e.message}}
document.getElementById('siteSettingsForm').onsubmit=async e=>{e.preventDefault();settingsMessage.textContent='Sparar…';try{await Promise.all([saveSetting('contact_phone',contactPhone.value.trim()),saveSetting('instagram_handle',instagramHandle.value.trim()),saveSetting('whatsapp_number',whatsappNumber.value.trim()),saveSetting('notification_email',notificationEmail.value.trim())]);settingsMessage.textContent='Kontaktinställningarna är sparade.'}catch(err){settingsMessage.textContent='Fel: '+err.message}};
document.getElementById('testWhatsappBtn').onclick=()=>{const raw=whatsappNumber.value.replace(/[^0-9]/g,'');if(!raw)return alert('Fyll i WhatsApp-numret först.');window.open(`https://wa.me/${raw}?text=${encodeURIComponent('Test från Blendxo Cuts adminpanel')}`,'_blank','noopener')};
document.getElementById('passwordForm').onsubmit=async e=>{e.preventDefault();passwordMessage.textContent='';if(newPassword.value!==confirmPassword.value)return passwordMessage.textContent='Lösenorden matchar inte.';const{error}=await sb.auth.updateUser({password:newPassword.value});passwordMessage.textContent=error?error.message:'Lösenordet är ändrat.';if(!error)e.target.reset()};
(async()=>{if(!configured){demoHint.textContent='Fyll i Supabase-inställningarna i supabase-config.js.';return}if(await authed())showAdmin()})();
