const cfg=window.BLENDXO_CONFIG||{};
const configured=cfg.mode==='supabase'&&cfg.supabaseUrl&&cfg.supabaseAnonKey;
const sb=configured?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const TIMES=['10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00'];
let services=[];
const esc=(v='')=>String(v).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
async function getServices(){if(!configured)return[];const{data,error}=await sb.from('services').select('*').eq('active',true).order('sort_order');if(error)throw error;return data||[]}
async function getImages(){if(!configured)return{};const{data,error}=await sb.from('site_images').select('image_key,url');if(error)throw error;return Object.fromEntries((data||[]).map(x=>[x.image_key,x.url]))}
async function getBookedTimes(date){if(!configured||!date)return[];const{data,error}=await sb.rpc('get_booked_times',{p_date:date});if(error)throw error;return (data||[]).map(x=>x.booking_time)}
async function refreshTimes(){const date=document.getElementById('bookingDate').value, sel=document.getElementById('bookingTime');sel.innerHTML='<option value="">Hämtar lediga tider…</option>';sel.disabled=true;try{const busy=await getBookedTimes(date);sel.innerHTML='<option value="">Välj tid</option>'+TIMES.filter(t=>!busy.includes(t)).map(t=>`<option value="${t}">${t}</option>`).join('');if(TIMES.every(t=>busy.includes(t)))sel.innerHTML='<option value="">Inga lediga tider detta datum</option>'}catch(e){console.error(e);sel.innerHTML='<option value="">Kunde inte hämta tider</option>'}finally{sel.disabled=false;updateSummary()}}
async function createBooking(payload){const{data,error}=await sb.from('bookings').insert(payload).select().single();if(error)throw error;try{await sb.functions.invoke('notify-booking',{body:{booking_id:data.id}})}catch(e){console.warn('Notis ej konfigurerad',e)}return data}
function updateSummary(){const s=services.find(x=>x.id===document.getElementById('bookingService').value),d=document.getElementById('bookingDate').value,t=document.getElementById('bookingTime').value;document.getElementById('bookingSummary').innerHTML=s?`<b>${esc(s.name)}</b><span>${s.price} kr • ${s.duration} min${d?' • '+esc(d):''}${t?' kl. '+esc(t):''}</span>`:'Välj en tjänst för att se bokningssammanfattningen.'}
async function init(){
 document.getElementById('year').textContent=new Date().getFullYear();
 const form=document.getElementById('bookingForm'),date=document.getElementById('bookingDate'),serviceSel=document.getElementById('bookingService'),timeSel=document.getElementById('bookingTime');date.min=new Date().toISOString().split('T')[0];
 if(!configured){form.innerHTML='<div class="notice"><b>Bokningen väntar på Supabase-konfiguration.</b><p>Fyll i Project URL och publishable/anon key i <code>supabase-config.js</code>.</p></div>';return}
 try{services=await getServices();serviceSel.innerHTML='<option value="">Välj tjänst</option>'+services.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} – ${s.price} kr</option>`).join('');document.getElementById('serviceGrid').innerHTML=services.map(s=>`<article class="service-card"><div class="service-icon">✦</div><h3>${esc(s.name)}</h3><strong>${s.price} kr</strong><p>Ca ${s.duration} min</p><a href="#boka" class="btn ghost btn-small book-service" data-id="${esc(s.id)}">Boka</a></article>`).join('');
 document.querySelectorAll('.book-service').forEach(a=>a.onclick=()=>{serviceSel.value=a.dataset.id;updateSummary()});
 const images=await getImages();document.querySelectorAll('.image-slot').forEach(el=>{const u=images[el.dataset.imageKey];if(u){el.style.backgroundImage=`url("${u}")`;el.classList.add('has-image')}});document.getElementById('galleryGrid').innerHTML=['gallery1','gallery2','gallery3','gallery4'].map((k,i)=>images[k]?`<div class="gallery-item" style="background-image:url('${images[k]}')"></div>`:`<div class="gallery-item placeholder"><span>LOOK ${i+1}</span><small>Lägg till via admin</small></div>`).join('');
 date.onchange=refreshTimes;serviceSel.onchange=updateSummary;timeSel.onchange=updateSummary;
 form.onsubmit=async e=>{e.preventDefault();const service=services.find(s=>s.id===serviceSel.value);if(!service)return;const payload={service_id:service.id,service_name:service.name,price:service.price,booking_date:date.value,booking_time:timeSel.value,customer_name:document.getElementById('bookingName').value.trim(),phone:document.getElementById('bookingPhone').value.trim(),note:document.getElementById('bookingNote').value.trim(),status:'pending'};try{await createBooking(payload);const box=document.getElementById('bookingSuccess');box.classList.remove('hidden');box.innerHTML=`<b>Tack ${esc(payload.customer_name)}!</b><br>${esc(service.name)} är bokad ${esc(payload.booking_date)} kl. ${esc(payload.booking_time)}.`;form.reset();await refreshTimes();box.scrollIntoView({behavior:'smooth',block:'center'})}catch(err){if(err.code==='23505')alert('Tiden hann precis bli bokad av någon annan. Välj nästa lediga tid.');else{console.error(err);alert('Bokningen kunde inte sparas. Försök igen.')}}};
 }catch(e){console.error(e);form.innerHTML='<div class="notice">Kunde inte ansluta till bokningssystemet. Kontrollera Supabase-konfigurationen.</div>'}
}
init();
