
let SITE=null,LANG="ar",CART=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function loadSite(){const r=await fetch("data.json?ts="+Date.now(),{cache:"no-store"});SITE=await r.json();LANG=SITE.store.defaultLanguage||"ar";renderSite()}
function money(v){v=Number(v)||0;return SITE.store.currency==="kr"?`${v.toFixed(2)} kr`:`${SITE.store.currency}${v.toFixed(2)}`}
function renderMedia(m,auto=false){if(!m)return"🎮";const url=esc(m.url);return m.type==="video"?`<video src="${url}" ${auto?"autoplay muted loop": "muted"} playsinline></video>`:`<img src="${url}" alt="">`}
function renderSite(){const t=SITE.content[LANG];document.documentElement.lang=LANG;document.documentElement.dir=LANG==="ar"?"rtl":"ltr";$("langBtn").textContent=LANG==="ar"?"EN":"AR";$("eyebrow").textContent=t.eyebrow;$("heroA").textContent=t.heroA;$("heroB").textContent=t.heroB;$("heroText").textContent=t.heroText;$("sectionTitle").textContent=t.sectionTitle;$("sectionSub").textContent=t.sectionSub;$("cartTitle").textContent=t.cart;$("heroCart").textContent="🛒 "+t.cart;$("productGrid").innerHTML=SITE.products.map(p=>`<article class="product"><div class="pmedia">${renderMedia(p.media?.[0])}<span class="badge">${esc(LANG==="ar"?p.badgeAr:p.badgeEn)}</span></div><div class="pbody"><h3>${esc(LANG==="ar"?p.titleAr:p.titleEn)}</h3><p>${esc(LANG==="ar"?p.descAr:p.descEn)}</p><div class="chips"><span class="chip">${esc(p.framework)}</span><span class="chip">v${esc(p.version)}</span></div><div class="bottom"><span class="price">${money(p.price)}</span><button class="add" onclick="addCart('${p.id}')">🛒 ${t.add}</button></div></div></article>`).join("");const p=SITE.products[0];if(p){$("heroMedia").innerHTML=renderMedia(p.media?.[0],true);$("featuredName").textContent=LANG==="ar"?p.titleAr:p.titleEn;$("featuredPrice").textContent=money(p.price)}renderCart()}
window.addCart=id=>{const p=SITE.products.find(x=>x.id===id);if(p&&!CART.find(x=>x.id===id))CART.push(p);renderCart();openCart()}
function renderCart(){const t=SITE?.content?.[LANG];if(!t)return;$("cartItems").innerHTML=CART.length?CART.map(p=>`<div class="cartItem"><strong>${esc(LANG==="ar"?p.titleAr:p.titleEn)}</strong><div>${money(p.price)}</div></div>`).join(""):`<div style="padding:45px 10px;text-align:center;color:#8e8595">${t.empty}</div>`;$("subtotal").textContent=money(CART.reduce((a,p)=>a+Number(p.price),0))}
function openCart(){$("drawer").classList.add("open");$("overlay").classList.add("show")}function closeCart(){$("drawer").classList.remove("open");$("overlay").classList.remove("show")}
$("cartBtn").onclick=openCart;$("heroCart").onclick=openCart;$("closeCart").onclick=closeCart;$("overlay").onclick=closeCart;$("langBtn").onclick=()=>{LANG=LANG==="ar"?"en":"ar";renderSite()}
function pay(url,name){if(!CART.length)return alert("Cart is empty");if(!url)return alert(`${name} link is not configured`);window.open(url,"_blank","noopener")}
$("payRevolut").onclick=()=>pay(SITE.store.revolutUrl,"Revolut");$("payPaypal").onclick=()=>pay(SITE.store.paypalUrl,"PayPal");
loadSite().catch(e=>{console.error(e);document.body.insertAdjacentHTML("afterbegin","<div style='padding:15px;background:#7f1d1d;color:white;text-align:center'>Kunde inte läsa data.json. Kontrollera att alla 7 filer ligger i GitHub.</div>")});
